### ISSUE TITLE
Unexpected error while optimizing: Undefined function or variable 'usearch'.

### ISSUE THREAD

**Issue by robaru** [acerbilab/bads#16]
Hi,
Thanks for this library. I have been using it for over two years without encountering any issues! :) 

I got one today that I am not able to get my head around it:

```
Undefined function or variable 'usearch'.

Error in bads (line 722)
        if ~options.AcqHedge && ~isempty(optimState.hedge) && ~isempty(usearch)
```

The error occurs randomly, meaning I cannot reproduce it systematically. However, with a few runs, I was able to repeat it and save the workspace [bads_bug.zip](https://github.com/acerbilab/bads/files/15318878/bads_bug.zip).

From a quick look, if the condition at line 560 is not met, the `usearch` variable is not defined, causing the error above.

Can I ask for some help with this? 

Thanks!

**Comment by lacerbi** [comment]
Thanks Roberto for the bug report!

Not sure why this is happening and specifically now, nothing has changed in the code recently so I presume there must be some super rare condition being triggered by your current problem.

Realistically, I won’t be able to look at this until June or even later in the summer due to my current workload. (The MATLAB version is maintained by myself, while there is a former student maintaining the Python version.)

**Comment by robaru** [comment]
I am also surprised and might have spotted what is causing this.

I did some testing, and by removing the field `TolFun` from the options, BADS did not throw the error. 

Since the `TolFun` parameter is not crucial for my analysis, I will avoid declaring it. 

Thanks!

**Comment by lacerbi** [comment]
Great to hear that you fixed it! Yeah, `TolFun` is not an officially supported option, it's part of the *advanced* options which you'd better not touch. The basic, supported options are the ones that you get from `bads('defaults')`.

Changes in the advanced options have not been tested (thoroughly or even at all), so any change is at your own risk.
If your function has an unusual scale, it is rather recommended that you rescale the output of your function such that the precision you need is of order `1e-3` (the default `TolFun`). I know, not ideal...
